### ISSUE TITLE
Downloading files using google drive fails

### ISSUE THREAD

**Issue by shyim** [blawar/nut#131]
```
127.0.0.1 - - [06/Sep/2019 23:46:55] "HEAD /api/file/gdrive/Switch/somensp.nsp HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 63602)
Traceback (most recent call last):
  File "C:\Users\shyim\Desktop\nut\Server\__init__.py", line 225, in do_HEAD
    method(request, response, **request.query)
  File "C:\Users\shyim\Desktop\nut\Server\Controller\Api.py", line 866, in getFile
    return downloadGdriveFile(response, path, start = start, end = end)
  File "C:\Users\shyim\Desktop\nut\Server\Controller\Api.py", line 835, in downloadGdriveFile
    return downloadProxyFile('https://www.googleapis.com/drive/v3/files/%s?alt=media' % info['id'], response, start, end, headers = {'Authorization': 'Bearer ' + creds.token })
  File "C:\Users\shyim\Desktop\nut\Server\Controller\Api.py", line 794, in downloadProxyFile
    response.write(chunk)
  File "C:\Users\shyim\Desktop\nut\Server\__init__.py", line 165, in write
    return self.handler.wfile.write(data)
  File "C:\Users\shyim\AppData\Local\Programs\Python\Python37\lib\socketserver.py", line 799, in write
    self._sock.sendall(b)
```

Directory Listing works :)

**Comment by blawar** [comment]
does the issue still persist?

**Comment by shyim** [comment]
Works now for me
