### ISSUE TITLE
Install from filebrowser listing fails

### ISSUE THREAD

**Issue by MDMAchine** [blawar/nut#163]
Running NUT 2.5 on a PI with Python 3.6.3.
Replicated on TF 6.2 and 7.0

This concerns the file browser. And appears to only happen in relation to servers that generate a file listing.

If I browse for a file and "open" a file everything is normal and installer options popup. However any other attempt after this fails on any server. This only happens if I have 2 or more locations enabled in the file browser that show a listing (tested nut and a remote https).

 The local NUT server console reports on any further attempt:

```
----------------------------------------
Exception happened during processing of request from ('192.168.2.140', 60013)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/NUT/Server/__init__.py", line 254, in __init__
    super(NutHandler, self).__init__(*args)
  File "/usr/local/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/home/pi/NUT/Server/__init__.py", line 265, in do_HEAD
    id, password = base64.b64decode(self.headers['Authorization'].split(' ')[1]).decode().split(':')
  File "/usr/local/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
----------------------------------------
```
If I have only 1 location enabled (that generates a listing) in file browser the issue goes away.

Using the New Games section everything appears to work fine unless the issue above is triggered beforehand.

**Comment by introkun** [comment]
@MDMAchine what protocol (NUT/NUTFS/etc) are you using?

**Comment by introkun** [comment]
>If I have only 1 location enabled (that generates a listing) in file browser the issue goes away.

Could you please add more details/steps on this @MDMAchine ?

**Comment by introkun** [comment]
@MDMAchine please try NUT version from the master branch and let us know
