### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by shawnhosg** [blawar/nut#172]
After executing "brew install libusb", I get 
"python ./nut.py 
Traceback (most recent call last):
  File "./nut.py", line 17, in <module>
    from nut import Nsps
  File "/Users/user/Documents/nut-master/nut/__init__.py", line 1, in <module>
    from nut import Nsps
  File "/Users/user/Documents/nut-master/nut/Nsps.py", line 6, in <module>
    from nut import Status
  File "/Users/user/Documents/nut-master/nut/Status.py", line 4, in <module>
    from nut import Config
  File "/Users/user/Documents/nut-master/nut/Config.py", line 113, in <module>
    load('conf/nut.default.conf')
  File "/Users/user/Documents/nut-master/nut/Config.py", line 89, in load
    with open(confFile, encoding="utf8") as f:
TypeError: 'encoding' is an invalid keyword argument for this function"

How do I fix this?

**Comment by shawnhosg** [comment]
nvm, on Mac OS Catalina 10.15.4, just ran it as "python3 nut.py" instead and it worked.
