### ISSUE TITLE
scrape not working

### ISSUE THREAD

**Issue by Dud3z** [blawar/nut#40]
after"python3 nut.py -s --scrape" i get following error.
```
Traceback (most recent call last):
  File "nut.py", line 20, in <module>
    from nut import Title
  File "/root/nut/nut/__init__.py", line 1, in <module>
    from nut import Titles
  File "/root/nut/nut/Titles.py", line 8, in <module>
    from nut import Title
  File "/root/nut/nut/Title.py", line 16, in <module>
    from nut import Nsps
  File "/root/nut/nut/Nsps.py", line 4, in <module>
    import Fs
  File "/root/nut/Fs/__init__.py", line 3, in <module>
    from Fs.Nsp import Nsp
  File "/root/nut/Fs/Nsp.py", line 19, in <module>
    from Fs.Ticket import Ticket
  File "/root/nut/Fs/Ticket.py", line 6, in <module>
    from nut import blockchain
  File "/root/nut/nut/blockchain.py", line 222
    print(f'{last_block}')
                        ^
SyntaxError: invalid syntax
```

please ignore im using it with root... this is just for testing ;-)

**Comment by ronaldmickey** [comment]
I don't think the dev is responding to bug reports and hasn't in a good while.

**Comment by throwawayay** [comment]
Update python and nut and try again
