### ISSUE TITLE
A guide on how to use the Remote Pull

### ISSUE THREAD

**Issue by felipecrs** [blawar/nut#465]
I'm trying to use the Remote Pull to download updates to my NSPs, but it simply does not work.

Is there a chance we can have some video or some comprehensive instructions on how to use it?

**Comment by shoyrock** [comment]
I tested it on macOS and Windows but no lock, hope a fix is added sometime soon

**Comment by shoyrock** [comment]
this is what I got when I tried using the pull option 
![Screenshot 2023-06-18 202349](https://github.com/blawar/nut/assets/51036435/0c8120f0-e8a1-4ce8-9bc0-98ce617160fb)
![Screenshot 2023-06-18 202349](https://github.com/blawar/nut/assets/51036435/1fd129ca-115e-4b27-beed-be1a3b42fd09)

**Comment by blawar** [comment]
I have only used  pull with ftp and local file system (mounted gdrive). Try mounting your gdrive to the local file system using rclone or google file stream, then configuring NUT to pull from the local path.

**Comment by felipecrs** [comment]
I was expecting I could use a remote pull server like pixelshop (https://github.com/carcaschoi/tinfoil-json) to download updates for my NSPs from within NUT.

Is my expectation correct?

**Comment by shoyrock** [comment]
> I was expecting I could use a remote pull server like Pixelshop (https://github.com/carcaschoi/tinfoil-json) to download updates for my NSPs from within NUT.
> 
> Is my expectation correct?

this is what I really wanted but I didn't see any way to get that done that's why I moved to pull from gdrive

**Comment by shoyrock** [comment]
> I have only used pull with ftp and local file system (mounted gdrive). Try mounting your gdrive to the local file system using rclone or google file stream, then configuring NUT to pull from the local path.

![image](https://github.com/blawar/nut/assets/51036435/81c43dd3-341c-40cb-a90a-9c8a4460f72a)
![image](https://github.com/blawar/nut/assets/51036435/6ecf27a1-8183-410a-a0ec-dad96816eb35)

seem to work, I don't think that I would be able to use this option with the docker version of nut

**Comment by felipecrs** [comment]
> seem to work

By simply clicking "Setup GDrive OAuth"? I wonder where does it pull assets from :)

> I don't think that I would be able to use this option with the docker version of nut

- In this case you should comment in #466 with more details on what's going wrong.

**Comment by shoyrock** [comment]
> > seem to work
> 
> By simply clicking "Setup GDrive OAuth"? I wonder where does it pull assets from :)
> 
> > I don't think that I would be able to use this option with the docker version of nut
> 
> * In this case you should comment in [Allow to run through docker #466](https://github.com/blawar/nut/pull/466) with more details on what's going wrong.

I'm using Nut via Unraid if this would work. ill be trying to mount Gdrive if that works then maybe, but still not a good fix

**Comment by andrea-ap** [comment]
i try setup gdrive OAuth , I followed the guide, created credentials, downloaded and hooked credentials.json file without errors, but when I go to remote pull paths and add gdrive , I get this error in Nut:
WARNING:googleapiclient.discovery_cache:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/discovery_cache/__init__.py", line 44, in autodetect
    from . import file_cache
  File "/usr/local/lib/python3.9/site-packages/googleapiclient/discovery_cache/file_cache.py", line 40, in <module>
    raise ImportError(
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
