### ISSUE TITLE
Issue installing pyqt5 dependency from requirements

### ISSUE THREAD

**Issue by PeadarNaCannai** [blawar/nut#474]
While all other dependencies seem to install fine, I'm unable to install pyqt5 from requirements.txt. Something about the metadata. Pasting the terminal window output below (only referring to pyqt5 since the rest was fine). When following Nut's Mac installation guide installing pyqt5 through homebrew was fine.

Was trying to look for solutions in other places but couldn't wrap my head around the workarounds... Does anyone here experience the same issue/has found a solution?

I'm on an M1 Mac running Monterey

```
Collecting pyqt5 (from qt-range-slider~=0.2.7->-r requirements.txt (line 20))
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/Users/pedrolatas/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nut/testnut/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/pedrolatas/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nut/testnut/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/pedrolatas/.pyenv/versions/3.9.7/lib/python3.9/site-packages/nut/testnut/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/q3/0hrvz6r13rv5009jf5cbrz600000gn/T/pip-build-env-w9c_wln5/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/q3/0hrvz6r13rv5009jf5cbrz600000gn/T/pip-build-env-w9c_wln5/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/q3/0hrvz6r13rv5009jf5cbrz600000gn/T/pip-build-env-w9c_wln5/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/q3/0hrvz6r13rv5009jf5cbrz600000gn/T/pip-install-yck5a6lf/pyqt5_179e78286f314a50b7eec92a2faffa18/project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/q3/0hrvz6r13rv5009jf5cbrz600000gn/T/pip-build-env-w9c_wln5/overlay/lib/python3.11/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/q3/0hrvz6r13rv5009jf5cbrz600000gn/T/pip-build-env-w9c_wln5/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/q3/0hrvz6r13rv5009jf5cbrz600000gn/T/pip-build-env-w9c_wln5/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by EvansJahja** [comment]
I had the same issue, but using 3.10.8 MSC on windows works for me while 3.11.4 GCC doesn't work for me.

**Comment by introkun** [comment]
Try this branch please https://github.com/blawar/nut/pull/490

**Comment by V-Karch** [comment]
I am now having this same issue running Raspbian. It won't install pyqt5

After seeing the suggestion to try the qt6 branch, that also resulted in the same issue, something about qmake, I can provide more detail later if this is looked at.

It's late at the time of writing this and I'm writing it from my mobile phone which is why I didn't provide too much info

**Comment by V-Karch** [comment]
@introkun @blawar 
Updated information:

OS: Raspbian GNU/Linux bookworm 12 armv7l
Host: Raspberry Pi 2 Model B Rev 1.1
Kernel: Linux 6.6.47+rpt-rpi-v7

Python version: 3.11.5 (also tested with 3.9.19)

Steps to reproduce:

```bash
$ git clone https://github.com/blawar/nut.git
$ cd nut
$ pip install -r requirements.txt
```

Full traceback:

```bash
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting requests~=2.26.0 (from -r requirements.txt (line 1))
  Using cached https://www.piwheels.org/simple/requests/requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting tqdm~=4.62.3 (from -r requirements.txt (line 2))
  Using cached https://www.piwheels.org/simple/tqdm/tqdm-4.62.3-py2.py3-none-any.whl (76 kB)
Collecting colorama~=0.4.4 (from -r requirements.txt (line 3))
  Using cached https://www.piwheels.org/simple/colorama/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting beautifulsoup4~=4.10.0 (from -r requirements.txt (line 4))
  Using cached https://www.piwheels.org/simple/beautifulsoup4/beautifulsoup4-4.10.0-py3-none-any.whl (96 kB)
Collecting urllib3~=1.26.7 (from -r requirements.txt (line 5))
  Using cached https://www.piwheels.org/simple/urllib3/urllib3-1.26.20-py2.py3-none-any.whl (144 kB)
Collecting pyusb~=1.2.1 (from -r requirements.txt (line 6))
  Using cached https://www.piwheels.org/simple/pyusb/pyusb-1.2.1-py3-none-any.whl (58 kB)
Collecting pyqt5~=5.15.6 (from -r requirements.txt (line 7))
  Using cached PyQt5-5.15.11.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/home/luna/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/luna/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/luna/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-_q0ty49t/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 28, in build_wheel
          project = AbstractProject.bootstrap('wheel',
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-_q0ty49t/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 74, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-_q0ty49t/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 608, in setup
          self.apply_user_defaults(tool)
        File "/tmp/pip-install-w34arfp5/pyqt5_dbac7e75c1b347adaa816c609009f97a/project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-_q0ty49t/overlay/lib/python3.11/site-packages/pyqtbuild/project.py", line 51, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/tmp/pip-build-env-_q0ty49t/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/tmp/pip-build-env-_q0ty49t/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 50, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
