### ISSUE TITLE
Adding file without ID causes Exception in thread Thread-4

### ISSUE THREAD

**Issue by coreduo0099** [blawar/nut#480]
Adding file without ID causes Exception in thread Thread-4

**To Reproduce**
Apparently, add a file that does not have TitleID correct

**Actual behaviour**
Application freezes

**Expected behaviour**
Warning vs Application error

added: H:\roms\Titles\HOT WHEELS UNLEASHED___ v0 (0100AA60136D2000) (BASE).nsp
could not get title id from filename, name needs to contain [titleId] : H:\roms\Titles\HOT WHEELS UNLEASHED___ v0 (0100AA60136D2000) (BASE).nsp
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "watchdog\observers\api.py", line 203, in run
  File "watchdog\observers\api.py", line 376, in dispatch_events
  File "watchdog\events.py", line 527, in dispatch
  File "watchdog\events.py", line 336, in dispatch
  File "Watcher.py", line 14, in on_created
  File "Nsps.py", line 31, in registerFile
  File "Fs\Nsp.py", line 41, in __init__
  File "Fs\IndexedFile.py", line 373, in setPath
  File "Fs\IndexedFile.py", line 88, in setHasValidTicket
  File "Fs\IndexedFile.py", line 77, in title
OSError: NSP no titleId set

**NUT version (or git hash):**
 - Nut: 3.3

**Additional context**
Windows 10 OS
I get similar errors with a full crash typically during "organize" but window closes before I can capture.  Will update when I can

**Comment by throwawayay** [comment]
Rename your files to have at least titleid in square brackets
