### ISSUE TITLE
Encoding issue when renaming. ' and é

### ISSUE THREAD

**Issue by S3phi40T** [blawar/nut#98]
There was issue with accents.

organizing
Traceback (most recent call last):
  File "nut.py", line 606, in <module>
    nut.organize()
  File "/srv/dev-disk-by-label-Malinka-Media/Home/sephirot/nut/nut/__init__.py", line 140, in organize
    f.move()
  File "/srv/dev-disk-by-label-Malinka-Media/Home/sephirot/nut/Fs/Nsp.py", line 252, in move
    if os.path.isfile(self.fileName()) and os.path.abspath(self.path) == os.path.abspath(self.fileName()):
  File "/usr/local/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2019' in position 21: ordinal not in range(128)

I have added 
#!/usr/bin/python3
# -*- coding: utf-8 -*-

to every file that was missing t.

Then there was an issue with 'é' like in Pokémon.
The unicode string for \xe9 is an accented e - é

It turned out both issues were in both "Let's go" Pokemon updates. and Tatsujin games.

**Comment by throwawayay** [comment]
Enable UTF-8 support on your terminal/command prompt
